<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'FileBank\Controller\FileController'          => __DIR__ . '/src/FileBank/Controller/FileController.php',
  'FileBank\Entity\File'                        => __DIR__ . '/src/FileBank/Entity/File.php',
  'FileBank\Entity\Keyword'                     => __DIR__ . '/src/FileBank/Entity/Keyword.php',
  'FileBank\Exception\ExceptionInterface'       => __DIR__ . '/src/FileBank/Exception/ExceptionInterface.php',
  'FileBank\Exception\FileNotFoundException'    => __DIR__ . '/src/FileBank/Exception/FileNotFoundException.php',
  'FileBank\Exception\InvalidArgumentException' => __DIR__ . '/src/FileBank/Exception/InvalidArgumentException.php',
  'FileBank\Exception\RuntimeException'         => __DIR__ . '/src/FileBank/Exception/RuntimeException.php',
  'FileBank\Filter\Octal'                       => __DIR__ . '/src/FileBank/Filter/Octal.php',
  'FileBank\Manager'                            => __DIR__ . '/src/FileBank/Manager.php',
  'FileBank\Module'                             => __DIR__ . '/src/FileBank/Module.php',
  'FileBank\Options\ModuleOptions'              => __DIR__ . '/src/FileBank/Options/ModuleOptions.php',
  'FileBank\Service\Factory'                    => __DIR__ . '/src/FileBank/Service/Factory.php',
  'FileBank\Validator\Chmod'                    => __DIR__ . '/src/FileBank/Validator/Chmod.php',
  'FileBank\Validator\Octal'                    => __DIR__ . '/src/FileBank/Validator/Octal.php',
  'FileBank\Version'                            => __DIR__ . '/src/FileBank/Version.php',
  'FileBank\View\Helper\FileBank'               => __DIR__ . '/src/FileBank/View/Helper/FileBank.php',
);
