<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'FileBank\Module'                       => __DIR__ . '/Module.php',
  'FileBank\Controller\FileController'    => __DIR__ . '/src/FileBank/Controller/FileController.php',
  'FileBank\Entity\File'                  => __DIR__ . '/src/FileBank/Entity/File.php',
  'FileBank\Entity\Keyword'               => __DIR__ . '/src/FileBank/Entity/Keyword.php',
  'FileBank\Exception\ExceptionInterface' => __DIR__ . '/src/FileBank/Exception/ExceptionInterface.php',
  'FileBank\Exception\RuntimeException'   => __DIR__ . '/src/FileBank/Exception/RuntimeException.php',
  'FileBank\Manager'                      => __DIR__ . '/src/FileBank/Manager.php',
  'FileBank\Service\Factory'              => __DIR__ . '/src/FileBank/Service/Factory.php',
  'FileBank\Version'                      => __DIR__ . '/src/FileBank/Version.php',
  'FileBank\View\Helper\FileBank'         => __DIR__ . '/src/FileBank/View/Helper/FileBank.php',
);
